// +build !ignore_autogenerated
/*
Copyright 2022 NDD.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by ndd-gen. DO NOT EDIT.

package v1alpha1

import nddv1 "github.com/yndd/ndd-runtime/apis/common/v1"

// GetActive of this SrlBfd.
func (mg *SrlBfd) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlBfd.
func (mg *SrlBfd) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlBfd.
func (mg *SrlBfd) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlBfd.
func (mg *SrlBfd) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlBfd.
func (mg *SrlBfd) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlBfd.
func (mg *SrlBfd) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlBfd.
func (mg *SrlBfd) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlBfd.
func (mg *SrlBfd) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlBfd.
func (mg *SrlBfd) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlBfd.
func (mg *SrlBfd) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlBfd.
func (mg *SrlBfd) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlBfd.
func (mg *SrlBfd) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlInterface.
func (mg *SrlInterface) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlInterface.
func (mg *SrlInterface) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlInterface.
func (mg *SrlInterface) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlInterface.
func (mg *SrlInterface) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlInterface.
func (mg *SrlInterface) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlInterface.
func (mg *SrlInterface) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlInterface.
func (mg *SrlInterface) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlInterface.
func (mg *SrlInterface) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlInterface.
func (mg *SrlInterface) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlInterface.
func (mg *SrlInterface) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlInterface.
func (mg *SrlInterface) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlInterface.
func (mg *SrlInterface) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlInterfaceSubinterface.
func (mg *SrlInterfaceSubinterface) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlInterfaceSubinterface.
func (mg *SrlInterfaceSubinterface) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlInterfaceSubinterface.
func (mg *SrlInterfaceSubinterface) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlInterfaceSubinterface.
func (mg *SrlInterfaceSubinterface) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlInterfaceSubinterface.
func (mg *SrlInterfaceSubinterface) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlInterfaceSubinterface.
func (mg *SrlInterfaceSubinterface) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlInterfaceSubinterface.
func (mg *SrlInterfaceSubinterface) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlInterfaceSubinterface.
func (mg *SrlInterfaceSubinterface) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlInterfaceSubinterface.
func (mg *SrlInterfaceSubinterface) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlInterfaceSubinterface.
func (mg *SrlInterfaceSubinterface) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlInterfaceSubinterface.
func (mg *SrlInterfaceSubinterface) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlInterfaceSubinterface.
func (mg *SrlInterfaceSubinterface) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlNetworkinstance.
func (mg *SrlNetworkinstance) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlNetworkinstance.
func (mg *SrlNetworkinstance) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlNetworkinstance.
func (mg *SrlNetworkinstance) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlNetworkinstance.
func (mg *SrlNetworkinstance) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlNetworkinstance.
func (mg *SrlNetworkinstance) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlNetworkinstance.
func (mg *SrlNetworkinstance) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlNetworkinstance.
func (mg *SrlNetworkinstance) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlNetworkinstance.
func (mg *SrlNetworkinstance) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlNetworkinstance.
func (mg *SrlNetworkinstance) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlNetworkinstance.
func (mg *SrlNetworkinstance) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlNetworkinstance.
func (mg *SrlNetworkinstance) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlNetworkinstance.
func (mg *SrlNetworkinstance) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlNetworkinstanceAggregateroutes.
func (mg *SrlNetworkinstanceAggregateroutes) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlNetworkinstanceAggregateroutes.
func (mg *SrlNetworkinstanceAggregateroutes) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlNetworkinstanceAggregateroutes.
func (mg *SrlNetworkinstanceAggregateroutes) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlNetworkinstanceAggregateroutes.
func (mg *SrlNetworkinstanceAggregateroutes) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlNetworkinstanceAggregateroutes.
func (mg *SrlNetworkinstanceAggregateroutes) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlNetworkinstanceAggregateroutes.
func (mg *SrlNetworkinstanceAggregateroutes) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlNetworkinstanceAggregateroutes.
func (mg *SrlNetworkinstanceAggregateroutes) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlNetworkinstanceAggregateroutes.
func (mg *SrlNetworkinstanceAggregateroutes) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlNetworkinstanceAggregateroutes.
func (mg *SrlNetworkinstanceAggregateroutes) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlNetworkinstanceAggregateroutes.
func (mg *SrlNetworkinstanceAggregateroutes) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlNetworkinstanceAggregateroutes.
func (mg *SrlNetworkinstanceAggregateroutes) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlNetworkinstanceAggregateroutes.
func (mg *SrlNetworkinstanceAggregateroutes) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlNetworkinstanceNexthopgroups.
func (mg *SrlNetworkinstanceNexthopgroups) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlNetworkinstanceNexthopgroups.
func (mg *SrlNetworkinstanceNexthopgroups) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlNetworkinstanceNexthopgroups.
func (mg *SrlNetworkinstanceNexthopgroups) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlNetworkinstanceNexthopgroups.
func (mg *SrlNetworkinstanceNexthopgroups) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlNetworkinstanceNexthopgroups.
func (mg *SrlNetworkinstanceNexthopgroups) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlNetworkinstanceNexthopgroups.
func (mg *SrlNetworkinstanceNexthopgroups) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlNetworkinstanceNexthopgroups.
func (mg *SrlNetworkinstanceNexthopgroups) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlNetworkinstanceNexthopgroups.
func (mg *SrlNetworkinstanceNexthopgroups) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlNetworkinstanceNexthopgroups.
func (mg *SrlNetworkinstanceNexthopgroups) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlNetworkinstanceNexthopgroups.
func (mg *SrlNetworkinstanceNexthopgroups) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlNetworkinstanceNexthopgroups.
func (mg *SrlNetworkinstanceNexthopgroups) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlNetworkinstanceNexthopgroups.
func (mg *SrlNetworkinstanceNexthopgroups) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlNetworkinstanceProtocolsBgp.
func (mg *SrlNetworkinstanceProtocolsBgp) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlNetworkinstanceProtocolsBgp.
func (mg *SrlNetworkinstanceProtocolsBgp) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlNetworkinstanceProtocolsBgp.
func (mg *SrlNetworkinstanceProtocolsBgp) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlNetworkinstanceProtocolsBgp.
func (mg *SrlNetworkinstanceProtocolsBgp) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlNetworkinstanceProtocolsBgp.
func (mg *SrlNetworkinstanceProtocolsBgp) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlNetworkinstanceProtocolsBgp.
func (mg *SrlNetworkinstanceProtocolsBgp) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlNetworkinstanceProtocolsBgp.
func (mg *SrlNetworkinstanceProtocolsBgp) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlNetworkinstanceProtocolsBgp.
func (mg *SrlNetworkinstanceProtocolsBgp) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlNetworkinstanceProtocolsBgp.
func (mg *SrlNetworkinstanceProtocolsBgp) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlNetworkinstanceProtocolsBgp.
func (mg *SrlNetworkinstanceProtocolsBgp) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlNetworkinstanceProtocolsBgp.
func (mg *SrlNetworkinstanceProtocolsBgp) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlNetworkinstanceProtocolsBgp.
func (mg *SrlNetworkinstanceProtocolsBgp) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlNetworkinstanceProtocolsBgpevpn.
func (mg *SrlNetworkinstanceProtocolsBgpevpn) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlNetworkinstanceProtocolsBgpevpn.
func (mg *SrlNetworkinstanceProtocolsBgpevpn) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlNetworkinstanceProtocolsBgpevpn.
func (mg *SrlNetworkinstanceProtocolsBgpevpn) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlNetworkinstanceProtocolsBgpevpn.
func (mg *SrlNetworkinstanceProtocolsBgpevpn) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlNetworkinstanceProtocolsBgpevpn.
func (mg *SrlNetworkinstanceProtocolsBgpevpn) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlNetworkinstanceProtocolsBgpevpn.
func (mg *SrlNetworkinstanceProtocolsBgpevpn) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlNetworkinstanceProtocolsBgpevpn.
func (mg *SrlNetworkinstanceProtocolsBgpevpn) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlNetworkinstanceProtocolsBgpevpn.
func (mg *SrlNetworkinstanceProtocolsBgpevpn) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlNetworkinstanceProtocolsBgpevpn.
func (mg *SrlNetworkinstanceProtocolsBgpevpn) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlNetworkinstanceProtocolsBgpevpn.
func (mg *SrlNetworkinstanceProtocolsBgpevpn) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlNetworkinstanceProtocolsBgpevpn.
func (mg *SrlNetworkinstanceProtocolsBgpevpn) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlNetworkinstanceProtocolsBgpevpn.
func (mg *SrlNetworkinstanceProtocolsBgpevpn) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlNetworkinstanceProtocolsBgpvpn.
func (mg *SrlNetworkinstanceProtocolsBgpvpn) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlNetworkinstanceProtocolsBgpvpn.
func (mg *SrlNetworkinstanceProtocolsBgpvpn) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlNetworkinstanceProtocolsBgpvpn.
func (mg *SrlNetworkinstanceProtocolsBgpvpn) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlNetworkinstanceProtocolsBgpvpn.
func (mg *SrlNetworkinstanceProtocolsBgpvpn) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlNetworkinstanceProtocolsBgpvpn.
func (mg *SrlNetworkinstanceProtocolsBgpvpn) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlNetworkinstanceProtocolsBgpvpn.
func (mg *SrlNetworkinstanceProtocolsBgpvpn) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlNetworkinstanceProtocolsBgpvpn.
func (mg *SrlNetworkinstanceProtocolsBgpvpn) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlNetworkinstanceProtocolsBgpvpn.
func (mg *SrlNetworkinstanceProtocolsBgpvpn) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlNetworkinstanceProtocolsBgpvpn.
func (mg *SrlNetworkinstanceProtocolsBgpvpn) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlNetworkinstanceProtocolsBgpvpn.
func (mg *SrlNetworkinstanceProtocolsBgpvpn) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlNetworkinstanceProtocolsBgpvpn.
func (mg *SrlNetworkinstanceProtocolsBgpvpn) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlNetworkinstanceProtocolsBgpvpn.
func (mg *SrlNetworkinstanceProtocolsBgpvpn) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlNetworkinstanceProtocolsIsis.
func (mg *SrlNetworkinstanceProtocolsIsis) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlNetworkinstanceProtocolsIsis.
func (mg *SrlNetworkinstanceProtocolsIsis) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlNetworkinstanceProtocolsIsis.
func (mg *SrlNetworkinstanceProtocolsIsis) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlNetworkinstanceProtocolsIsis.
func (mg *SrlNetworkinstanceProtocolsIsis) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlNetworkinstanceProtocolsIsis.
func (mg *SrlNetworkinstanceProtocolsIsis) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlNetworkinstanceProtocolsIsis.
func (mg *SrlNetworkinstanceProtocolsIsis) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlNetworkinstanceProtocolsIsis.
func (mg *SrlNetworkinstanceProtocolsIsis) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlNetworkinstanceProtocolsIsis.
func (mg *SrlNetworkinstanceProtocolsIsis) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlNetworkinstanceProtocolsIsis.
func (mg *SrlNetworkinstanceProtocolsIsis) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlNetworkinstanceProtocolsIsis.
func (mg *SrlNetworkinstanceProtocolsIsis) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlNetworkinstanceProtocolsIsis.
func (mg *SrlNetworkinstanceProtocolsIsis) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlNetworkinstanceProtocolsIsis.
func (mg *SrlNetworkinstanceProtocolsIsis) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlNetworkinstanceProtocolsLinux.
func (mg *SrlNetworkinstanceProtocolsLinux) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlNetworkinstanceProtocolsLinux.
func (mg *SrlNetworkinstanceProtocolsLinux) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlNetworkinstanceProtocolsLinux.
func (mg *SrlNetworkinstanceProtocolsLinux) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlNetworkinstanceProtocolsLinux.
func (mg *SrlNetworkinstanceProtocolsLinux) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlNetworkinstanceProtocolsLinux.
func (mg *SrlNetworkinstanceProtocolsLinux) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlNetworkinstanceProtocolsLinux.
func (mg *SrlNetworkinstanceProtocolsLinux) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlNetworkinstanceProtocolsLinux.
func (mg *SrlNetworkinstanceProtocolsLinux) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlNetworkinstanceProtocolsLinux.
func (mg *SrlNetworkinstanceProtocolsLinux) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlNetworkinstanceProtocolsLinux.
func (mg *SrlNetworkinstanceProtocolsLinux) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlNetworkinstanceProtocolsLinux.
func (mg *SrlNetworkinstanceProtocolsLinux) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlNetworkinstanceProtocolsLinux.
func (mg *SrlNetworkinstanceProtocolsLinux) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlNetworkinstanceProtocolsLinux.
func (mg *SrlNetworkinstanceProtocolsLinux) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlNetworkinstanceProtocolsOspf.
func (mg *SrlNetworkinstanceProtocolsOspf) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlNetworkinstanceProtocolsOspf.
func (mg *SrlNetworkinstanceProtocolsOspf) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlNetworkinstanceProtocolsOspf.
func (mg *SrlNetworkinstanceProtocolsOspf) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlNetworkinstanceProtocolsOspf.
func (mg *SrlNetworkinstanceProtocolsOspf) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlNetworkinstanceProtocolsOspf.
func (mg *SrlNetworkinstanceProtocolsOspf) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlNetworkinstanceProtocolsOspf.
func (mg *SrlNetworkinstanceProtocolsOspf) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlNetworkinstanceProtocolsOspf.
func (mg *SrlNetworkinstanceProtocolsOspf) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlNetworkinstanceProtocolsOspf.
func (mg *SrlNetworkinstanceProtocolsOspf) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlNetworkinstanceProtocolsOspf.
func (mg *SrlNetworkinstanceProtocolsOspf) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlNetworkinstanceProtocolsOspf.
func (mg *SrlNetworkinstanceProtocolsOspf) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlNetworkinstanceProtocolsOspf.
func (mg *SrlNetworkinstanceProtocolsOspf) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlNetworkinstanceProtocolsOspf.
func (mg *SrlNetworkinstanceProtocolsOspf) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlNetworkinstanceStaticroutes.
func (mg *SrlNetworkinstanceStaticroutes) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlNetworkinstanceStaticroutes.
func (mg *SrlNetworkinstanceStaticroutes) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlNetworkinstanceStaticroutes.
func (mg *SrlNetworkinstanceStaticroutes) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlNetworkinstanceStaticroutes.
func (mg *SrlNetworkinstanceStaticroutes) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlNetworkinstanceStaticroutes.
func (mg *SrlNetworkinstanceStaticroutes) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlNetworkinstanceStaticroutes.
func (mg *SrlNetworkinstanceStaticroutes) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlNetworkinstanceStaticroutes.
func (mg *SrlNetworkinstanceStaticroutes) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlNetworkinstanceStaticroutes.
func (mg *SrlNetworkinstanceStaticroutes) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlNetworkinstanceStaticroutes.
func (mg *SrlNetworkinstanceStaticroutes) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlNetworkinstanceStaticroutes.
func (mg *SrlNetworkinstanceStaticroutes) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlNetworkinstanceStaticroutes.
func (mg *SrlNetworkinstanceStaticroutes) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlNetworkinstanceStaticroutes.
func (mg *SrlNetworkinstanceStaticroutes) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlRoutingpolicyAspathset.
func (mg *SrlRoutingpolicyAspathset) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlRoutingpolicyAspathset.
func (mg *SrlRoutingpolicyAspathset) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlRoutingpolicyAspathset.
func (mg *SrlRoutingpolicyAspathset) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlRoutingpolicyAspathset.
func (mg *SrlRoutingpolicyAspathset) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlRoutingpolicyAspathset.
func (mg *SrlRoutingpolicyAspathset) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlRoutingpolicyAspathset.
func (mg *SrlRoutingpolicyAspathset) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlRoutingpolicyAspathset.
func (mg *SrlRoutingpolicyAspathset) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlRoutingpolicyAspathset.
func (mg *SrlRoutingpolicyAspathset) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlRoutingpolicyAspathset.
func (mg *SrlRoutingpolicyAspathset) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlRoutingpolicyAspathset.
func (mg *SrlRoutingpolicyAspathset) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlRoutingpolicyAspathset.
func (mg *SrlRoutingpolicyAspathset) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlRoutingpolicyAspathset.
func (mg *SrlRoutingpolicyAspathset) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlRoutingpolicyCommunityset.
func (mg *SrlRoutingpolicyCommunityset) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlRoutingpolicyCommunityset.
func (mg *SrlRoutingpolicyCommunityset) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlRoutingpolicyCommunityset.
func (mg *SrlRoutingpolicyCommunityset) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlRoutingpolicyCommunityset.
func (mg *SrlRoutingpolicyCommunityset) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlRoutingpolicyCommunityset.
func (mg *SrlRoutingpolicyCommunityset) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlRoutingpolicyCommunityset.
func (mg *SrlRoutingpolicyCommunityset) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlRoutingpolicyCommunityset.
func (mg *SrlRoutingpolicyCommunityset) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlRoutingpolicyCommunityset.
func (mg *SrlRoutingpolicyCommunityset) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlRoutingpolicyCommunityset.
func (mg *SrlRoutingpolicyCommunityset) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlRoutingpolicyCommunityset.
func (mg *SrlRoutingpolicyCommunityset) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlRoutingpolicyCommunityset.
func (mg *SrlRoutingpolicyCommunityset) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlRoutingpolicyCommunityset.
func (mg *SrlRoutingpolicyCommunityset) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlRoutingpolicyPolicy.
func (mg *SrlRoutingpolicyPolicy) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlRoutingpolicyPolicy.
func (mg *SrlRoutingpolicyPolicy) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlRoutingpolicyPolicy.
func (mg *SrlRoutingpolicyPolicy) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlRoutingpolicyPolicy.
func (mg *SrlRoutingpolicyPolicy) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlRoutingpolicyPolicy.
func (mg *SrlRoutingpolicyPolicy) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlRoutingpolicyPolicy.
func (mg *SrlRoutingpolicyPolicy) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlRoutingpolicyPolicy.
func (mg *SrlRoutingpolicyPolicy) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlRoutingpolicyPolicy.
func (mg *SrlRoutingpolicyPolicy) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlRoutingpolicyPolicy.
func (mg *SrlRoutingpolicyPolicy) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlRoutingpolicyPolicy.
func (mg *SrlRoutingpolicyPolicy) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlRoutingpolicyPolicy.
func (mg *SrlRoutingpolicyPolicy) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlRoutingpolicyPolicy.
func (mg *SrlRoutingpolicyPolicy) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlRoutingpolicyPrefixset.
func (mg *SrlRoutingpolicyPrefixset) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlRoutingpolicyPrefixset.
func (mg *SrlRoutingpolicyPrefixset) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlRoutingpolicyPrefixset.
func (mg *SrlRoutingpolicyPrefixset) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlRoutingpolicyPrefixset.
func (mg *SrlRoutingpolicyPrefixset) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlRoutingpolicyPrefixset.
func (mg *SrlRoutingpolicyPrefixset) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlRoutingpolicyPrefixset.
func (mg *SrlRoutingpolicyPrefixset) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlRoutingpolicyPrefixset.
func (mg *SrlRoutingpolicyPrefixset) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlRoutingpolicyPrefixset.
func (mg *SrlRoutingpolicyPrefixset) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlRoutingpolicyPrefixset.
func (mg *SrlRoutingpolicyPrefixset) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlRoutingpolicyPrefixset.
func (mg *SrlRoutingpolicyPrefixset) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlRoutingpolicyPrefixset.
func (mg *SrlRoutingpolicyPrefixset) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlRoutingpolicyPrefixset.
func (mg *SrlRoutingpolicyPrefixset) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlSystemName.
func (mg *SrlSystemName) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlSystemName.
func (mg *SrlSystemName) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlSystemName.
func (mg *SrlSystemName) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlSystemName.
func (mg *SrlSystemName) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlSystemName.
func (mg *SrlSystemName) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlSystemName.
func (mg *SrlSystemName) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlSystemName.
func (mg *SrlSystemName) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlSystemName.
func (mg *SrlSystemName) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlSystemName.
func (mg *SrlSystemName) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlSystemName.
func (mg *SrlSystemName) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlSystemName.
func (mg *SrlSystemName) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlSystemName.
func (mg *SrlSystemName) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlSystemNetworkinstanceProtocolsBgpvpn.
func (mg *SrlSystemNetworkinstanceProtocolsBgpvpn) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlSystemNetworkinstanceProtocolsBgpvpn.
func (mg *SrlSystemNetworkinstanceProtocolsBgpvpn) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlSystemNetworkinstanceProtocolsBgpvpn.
func (mg *SrlSystemNetworkinstanceProtocolsBgpvpn) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlSystemNetworkinstanceProtocolsBgpvpn.
func (mg *SrlSystemNetworkinstanceProtocolsBgpvpn) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlSystemNetworkinstanceProtocolsBgpvpn.
func (mg *SrlSystemNetworkinstanceProtocolsBgpvpn) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlSystemNetworkinstanceProtocolsBgpvpn.
func (mg *SrlSystemNetworkinstanceProtocolsBgpvpn) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlSystemNetworkinstanceProtocolsBgpvpn.
func (mg *SrlSystemNetworkinstanceProtocolsBgpvpn) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlSystemNetworkinstanceProtocolsBgpvpn.
func (mg *SrlSystemNetworkinstanceProtocolsBgpvpn) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlSystemNetworkinstanceProtocolsBgpvpn.
func (mg *SrlSystemNetworkinstanceProtocolsBgpvpn) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlSystemNetworkinstanceProtocolsBgpvpn.
func (mg *SrlSystemNetworkinstanceProtocolsBgpvpn) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlSystemNetworkinstanceProtocolsBgpvpn.
func (mg *SrlSystemNetworkinstanceProtocolsBgpvpn) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlSystemNetworkinstanceProtocolsBgpvpn.
func (mg *SrlSystemNetworkinstanceProtocolsBgpvpn) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlSystemNetworkinstanceProtocolsEvpn.
func (mg *SrlSystemNetworkinstanceProtocolsEvpn) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlSystemNetworkinstanceProtocolsEvpn.
func (mg *SrlSystemNetworkinstanceProtocolsEvpn) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlSystemNetworkinstanceProtocolsEvpn.
func (mg *SrlSystemNetworkinstanceProtocolsEvpn) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlSystemNetworkinstanceProtocolsEvpn.
func (mg *SrlSystemNetworkinstanceProtocolsEvpn) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlSystemNetworkinstanceProtocolsEvpn.
func (mg *SrlSystemNetworkinstanceProtocolsEvpn) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlSystemNetworkinstanceProtocolsEvpn.
func (mg *SrlSystemNetworkinstanceProtocolsEvpn) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlSystemNetworkinstanceProtocolsEvpn.
func (mg *SrlSystemNetworkinstanceProtocolsEvpn) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlSystemNetworkinstanceProtocolsEvpn.
func (mg *SrlSystemNetworkinstanceProtocolsEvpn) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlSystemNetworkinstanceProtocolsEvpn.
func (mg *SrlSystemNetworkinstanceProtocolsEvpn) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlSystemNetworkinstanceProtocolsEvpn.
func (mg *SrlSystemNetworkinstanceProtocolsEvpn) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlSystemNetworkinstanceProtocolsEvpn.
func (mg *SrlSystemNetworkinstanceProtocolsEvpn) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlSystemNetworkinstanceProtocolsEvpn.
func (mg *SrlSystemNetworkinstanceProtocolsEvpn) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstance) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi.
func (mg *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsi) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlSystemNtp.
func (mg *SrlSystemNtp) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlSystemNtp.
func (mg *SrlSystemNtp) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlSystemNtp.
func (mg *SrlSystemNtp) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlSystemNtp.
func (mg *SrlSystemNtp) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlSystemNtp.
func (mg *SrlSystemNtp) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlSystemNtp.
func (mg *SrlSystemNtp) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlSystemNtp.
func (mg *SrlSystemNtp) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlSystemNtp.
func (mg *SrlSystemNtp) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlSystemNtp.
func (mg *SrlSystemNtp) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlSystemNtp.
func (mg *SrlSystemNtp) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlSystemNtp.
func (mg *SrlSystemNtp) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlSystemNtp.
func (mg *SrlSystemNtp) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlTunnelinterface.
func (mg *SrlTunnelinterface) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlTunnelinterface.
func (mg *SrlTunnelinterface) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlTunnelinterface.
func (mg *SrlTunnelinterface) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlTunnelinterface.
func (mg *SrlTunnelinterface) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlTunnelinterface.
func (mg *SrlTunnelinterface) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlTunnelinterface.
func (mg *SrlTunnelinterface) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlTunnelinterface.
func (mg *SrlTunnelinterface) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlTunnelinterface.
func (mg *SrlTunnelinterface) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlTunnelinterface.
func (mg *SrlTunnelinterface) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlTunnelinterface.
func (mg *SrlTunnelinterface) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlTunnelinterface.
func (mg *SrlTunnelinterface) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlTunnelinterface.
func (mg *SrlTunnelinterface) SetTarget(t []string) {
	mg.Status.Target = t
}

// GetActive of this SrlTunnelinterfaceVxlaninterface.
func (mg *SrlTunnelinterfaceVxlaninterface) GetActive() bool {
	return mg.Spec.Active
}

// GetDeletionPolicy of this SrlTunnelinterfaceVxlaninterface.
func (mg *SrlTunnelinterfaceVxlaninterface) GetDeletionPolicy() nddv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetExternalLeafRefs of this SrlTunnelinterfaceVxlaninterface.
func (mg *SrlTunnelinterfaceVxlaninterface) GetExternalLeafRefs() []string {
	return mg.Status.ExternalLeafRefs
}

// GetNetworkNodeReference of this SrlTunnelinterfaceVxlaninterface.
func (mg *SrlTunnelinterfaceVxlaninterface) GetNetworkNodeReference() *nddv1.Reference {
	return mg.Spec.NetworkNodeReference
}

// GetResourceIndexes of this SrlTunnelinterfaceVxlaninterface.
func (mg *SrlTunnelinterfaceVxlaninterface) GetResourceIndexes() map[string]string {
	return mg.Status.ResourceIndexes
}

// GetTarget of this SrlTunnelinterfaceVxlaninterface.
func (mg *SrlTunnelinterfaceVxlaninterface) GetTarget() []string {
	return mg.Status.Target
}

// SetActive of this SrlTunnelinterfaceVxlaninterface.
func (mg *SrlTunnelinterfaceVxlaninterface) SetActive(b bool) {
	mg.Spec.Active = b
}

// SetDeletionPolicy of this SrlTunnelinterfaceVxlaninterface.
func (mg *SrlTunnelinterfaceVxlaninterface) SetDeletionPolicy(r nddv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetExternalLeafRefs of this SrlTunnelinterfaceVxlaninterface.
func (mg *SrlTunnelinterfaceVxlaninterface) SetExternalLeafRefs(n []string) {
	mg.Status.ExternalLeafRefs = n
}

// SetNetworkNodeReference of this SrlTunnelinterfaceVxlaninterface.
func (mg *SrlTunnelinterfaceVxlaninterface) SetNetworkNodeReference(r *nddv1.Reference) {
	mg.Spec.NetworkNodeReference = r
}

// SetResourceIndexes of this SrlTunnelinterfaceVxlaninterface.
func (mg *SrlTunnelinterfaceVxlaninterface) SetResourceIndexes(n map[string]string) {
	mg.Status.ResourceIndexes = n
}

// SetTarget of this SrlTunnelinterfaceVxlaninterface.
func (mg *SrlTunnelinterfaceVxlaninterface) SetTarget(t []string) {
	mg.Status.Target = t
}
