//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 NDD.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by ndd-gen. DO NOT EDIT.

package v1alpha1

import resource "github.com/yndd/ndd-runtime/pkg/resource"

// GetItems of this SrlBfdList.
func (l *SrlBfdList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlInterfaceList.
func (l *SrlInterfaceList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlInterfaceSubinterfaceList.
func (l *SrlInterfaceSubinterfaceList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlNetworkinstanceAggregateroutesList.
func (l *SrlNetworkinstanceAggregateroutesList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlNetworkinstanceList.
func (l *SrlNetworkinstanceList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlNetworkinstanceNexthopgroupsList.
func (l *SrlNetworkinstanceNexthopgroupsList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlNetworkinstanceProtocolsBgpList.
func (l *SrlNetworkinstanceProtocolsBgpList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlNetworkinstanceProtocolsBgpevpnList.
func (l *SrlNetworkinstanceProtocolsBgpevpnList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlNetworkinstanceProtocolsBgpvpnList.
func (l *SrlNetworkinstanceProtocolsBgpvpnList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlNetworkinstanceProtocolsIsisList.
func (l *SrlNetworkinstanceProtocolsIsisList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlNetworkinstanceProtocolsLinuxList.
func (l *SrlNetworkinstanceProtocolsLinuxList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlNetworkinstanceProtocolsOspfList.
func (l *SrlNetworkinstanceProtocolsOspfList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlNetworkinstanceStaticroutesList.
func (l *SrlNetworkinstanceStaticroutesList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlRoutingpolicyAspathsetList.
func (l *SrlRoutingpolicyAspathsetList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlRoutingpolicyCommunitysetList.
func (l *SrlRoutingpolicyCommunitysetList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlRoutingpolicyPolicyList.
func (l *SrlRoutingpolicyPolicyList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlRoutingpolicyPrefixsetList.
func (l *SrlRoutingpolicyPrefixsetList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlSystemNameList.
func (l *SrlSystemNameList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlSystemNetworkinstanceProtocolsBgpvpnList.
func (l *SrlSystemNetworkinstanceProtocolsBgpvpnList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsiList.
func (l *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceEsiList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceList.
func (l *SrlSystemNetworkinstanceProtocolsEvpnEsisBgpinstanceList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlSystemNetworkinstanceProtocolsEvpnList.
func (l *SrlSystemNetworkinstanceProtocolsEvpnList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlSystemNtpList.
func (l *SrlSystemNtpList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlTransactionList.
func (l *SrlTransactionList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlTunnelinterfaceList.
func (l *SrlTunnelinterfaceList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}

// GetItems of this SrlTunnelinterfaceVxlaninterfaceList.
func (l *SrlTunnelinterfaceVxlaninterfaceList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
